hajj/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = "Hajj App Admin"
admin.site.site_title = "Hajj App"
admin.site.index_title = "Welcome to Hajj App Admin"

from hajj import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('', include('dashboard.urls')),
    path('hajj_application/', include('hajj_application.urls')),
    path('', include('package_making.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hajj_application/urls.py
from django.urls import path

from hajj_application.views import CreateHajjApplication, ListHajjApplication, UpdateHajjApplication, \
    DeleteHajjApplication, DetailHajjApplication, GetPackage

app_name = 'hajj_application'
urlpatterns = [
    path('add', CreateHajjApplication.as_view(), name='add'),
    path('list', ListHajjApplication.as_view(), name='list'),
    path('update/<int:pk>', UpdateHajjApplication.as_view(), name='update'),
    path('delete/<int:pk>', DeleteHajjApplication.as_view(), name='delete'),
    path('detail/<int:pk>', DetailHajjApplication.as_view(), name='detail'),
    path('get_package', GetPackage.as_view(), name='get_package'),
]

master_data/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class RoomType(TimeStampModel):
    name = models.CharField(max_length=150, verbose_name='Room Type')
    capacity = models.PositiveIntegerField(verbose_name='Capacity')
    description = models.TextField(verbose_name='Description')

    def __str__(self):
        return self.name


# ==============
class Country(TimeStampModel):
    name = models.CharField(max_length=100, null=False, verbose_name='Courty Name', unique=True)
    code = models.CharField(max_length=5, null=False, verbose_name='Country Code', unique=True)

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


class City(TimeStampModel):
    name = models.CharField(max_length=100, verbose_name='City Name', unique=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='Country')
    country_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Country Name')

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


@receiver(pre_save, sender=City)
def set_country_name(sender, instance, **kwargs):
    if instance.country:
        instance.country_name = instance.country.name
    else:
        instance.country_name = None

# ==============
class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Supplier(TimeStampModel):

    CURRENCIES = [
        ('USD', 'United States Dollar'),
        ('EUR', 'Euro'),
        ('JPY', 'Japanese Yen'),
        ('GBP', 'British Pound Sterling'),
        ('AUD', 'Australian Dollar'),
        ('CNY', 'Chinese Yuan'),
        ('INR', 'Indian Rupee'),
        ('AED', 'United Arab Emirates Dirham'),
        ('SAR', 'Saudi Riyal'),
        ('QAR', 'Qatari Riyal'),
        ('KWD', 'Kuwaiti Dinar'),
        ('OMR', 'Omani Rial'),
        ('BHD', 'Bahraini Dinar'),
        ('SGD', 'Singapore Dollar'),
        ('MYR', 'Malaysian Ringgit'),
        ('THB', 'Thai Baht'),
        ('IDR', 'Indonesian Rupiah'),
        ('PHP', 'Philippine Peso'),
        ('PKR', 'Pakistani Rupee'),
        ('BDT', 'Bangladeshi Taka'),
        ('LKR', 'Sri Lankan Rupee'),
    ]

    name = models.CharField(max_length=255, verbose_name='Supplier Name')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='Country')
    country_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Country Name')
    currency = models.CharField(max_length=3, choices=CURRENCIES, verbose_name='Currency')
    is_transporters = models.BooleanField(default=False, verbose_name='Transporter')
    is_hotel = models.BooleanField(default=False, verbose_name='Hotel')
    is_hotel_agent = models.BooleanField(default=False, verbose_name='Hotel Agent')
    is_visa_agent = models.BooleanField(default=False, verbose_name='Visa Agent')
    email = models.EmailField(verbose_name='Email')
    contact = models.CharField(max_length=15, verbose_name='Contact')
    contact_person = models.CharField(max_length=255, verbose_name='Contact Person')
    address = models.TextField(verbose_name='Address')
    class Meta:
        verbose_name = 'Supplier'
        verbose_name_plural = 'Suppliers'

    def __str__(self):
        return self.name


@receiver(pre_save, sender=Supplier)
def set_country_name(sender, instance, **kwargs):
    if instance.country:
        instance.country_name = instance.country.name
    else:
        instance.country_name = None

# ==============

hajj_application/forms.py
from django import forms

from hajj_application.models import HajjApplication


class HajjApplicationForm(forms.ModelForm):
    class Meta:
        model = HajjApplication
        fields = '__all__'
        exclude = ('user',)
        widgets = {
            'present_postal_address': forms.Textarea(attrs={'rows': 4}),
            'date_of_expiry': forms.DateInput(attrs={'type': 'date'}),
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(HajjApplicationForm, self).__init__(*args, **kwargs)

        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = "form-control"

    def save(self, *args, **kwargs):
        kwargs['commit'] = False
        obj = super(HajjApplicationForm, self).save(*args, **kwargs)
        if self.request:
            obj.user = self.request.user
            obj.save()
        return obj

hajj_application/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView

from hajj_application.forms import HajjApplicationForm
from hajj_application.models import HajjApplication
from package_making.models import Package, PackageHotelItem


# ================================HajjApplication=============================
class CreateHajjApplication(CreateView):
    template_name = 'hajj_application/add.html'
    model = HajjApplication
    form_class = HajjApplicationForm
    success_url = "/hajj_application/list"

    # @method_decorator(privilegesRequired)
    # def dispatch(self, *args, **kwargs):
    #     return super(CreateCategory, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(CreateHajjApplication, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class ListHajjApplication(LoginRequiredMixin, ListView):
    template_name = 'hajj_application/list.html'
    context_object_name = 'hajj_application_items'
    model = HajjApplication

    # @method_decorator(privilegesRequired)
    # def dispatch(self, *args, **kwargs):
    #     return super(GetCategories, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        queryset = super(ListHajjApplication, self).get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ListHajjApplication, self).get_context_data(**kwargs)
        # context['tot_item_groups'] = ItemGroup.objects.count()
        # context['tot_sub_item_group'] = ItemGroup.objects.filter(parent__item_group__item_group=True).count()
        return context


#
#
class UpdateHajjApplication(UpdateView):
    model = HajjApplication
    form_class = HajjApplicationForm
    template_name = 'hajj_application/update.html'
    success_url = '/hajj_application/list'

    # @method_decorator(privilegesRequired)
    # def dispatch(self, *args, **kwargs):
    #     return super(UpdateCategory, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(UpdateHajjApplication, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class DetailHajjApplication(DetailView):
    model = HajjApplication
    context_object_name = 'hajj_application_item'
    template_name = 'hajj_application/detail.html'


class DeleteHajjApplication(DeleteView):
    model = HajjApplication
    success_url = '/hajj_application/list'


# ================================HajjApplication End============================
# ================================Fetching Package Information============================
class GetPackage(View):
    def serialize_package(self, package):
        return {
            'id': package.id,
            'package_name': package.name,
            'package_type': package.package_type,
            'maktab': package.maktab,
            'country': package.country_name,
            'package_days': package.package_days,
            'package_sale_price_sar': package.package_sale_price_sar,
            'exchange_rate': package.exchange_rate,
            'package_sale_price_pkr': package.package_sale_price_pkr,
            'terms_and_conditions': package.terms_and_conditions,
        }

    def package_hotel_items(self, package_item):
        return {
            'id': package_item.id,
            'city_name': package_item.city_name,
            'hotel_name': package_item.hotel_name,
            'room_type_name': package_item.room_type_name,
            'check_in_date': package_item.check_in_date,
            'check_out_date': package_item.check_out_date,
            'meal': package_item.meal,
            'nights': package_item.nights,
            'cost': package_item.cost,
            'currency': package_item.currency
        }

    def get(self, request, *args, **kwargs):
        package_id = request.GET.get('package_id')

        if package_id:
            # Fetching a single object
            package = get_object_or_404(Package, id=package_id)
            serialized_package = self.serialize_package(package)
            package_hotel_items = PackageHotelItem.objects.filter(package=package)
            serialized_package_hotel_items = [self.package_hotel_items(package_item) for package_item in package_hotel_items]
            return JsonResponse({'package': serialized_package, 'success': True, 'package_items': serialized_package_hotel_items})
        return JsonResponse({'success': False})

templates/hajj_application/detail.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Detail Application{% endblock %}</title>
{% block content %}
    <div class="heading-container">
        <h5 class="heading">Detail Application</h5>
    </div>
    <div class="ro-outer">
        <a href="{% url 'hajj_application:list' %}">
            <span class=" new_button button-green "> All Applications</span>
        </a>
        <span type="button" class="close_btn button-red" aria-hidden="true"
              onClick="javascript:history.go(-1);">X</span>
    </div>
    <table id="detail_application">
        <tbody>
        <tr>
            <td>Hajj Application #</td>
            <td>{{ hajj_application_item.hajj_application_no }}</td>

            <td>Enrollment #</td>
            <td>{{ hajj_application_item.enrollment_no }}</td>
        </tr>
        <tr>

            <td>Group Coordinator Application #</td>
            <td>{{ hajj_application_item.group_coordinator_application_no }}</td>

            <td>HGO #</td>
            <td>{{ hajj_application_item.hgo_no }}</td>
        </tr>
        <tr>

            <td>Stay Duration</td>
            <td>{{ hajj_application_item.stay_duration }}</td>

            <td>Substituted Against Application No</td>
            <td>{{ hajj_application_item.substituted_against_application_no }}</td>
        </tr>

        <!-- Row 2 -->
        <tr>
            <td>{{ hajj_application_item.name_of_applicant_as_per_passport.label_tag }}</td>
            <td>{{ hajj_application_item.name_of_applicant_as_per_passport }}</td>

            <td>{{ hajj_application_item.sur_name.label_tag }}</td>
            <td>{{ hajj_application_item.sur_name }}</td>

            <td>{{ hajj_application_item.given_name.label_tag }}</td>
            <td>{{ hajj_application_item.given_name }}</td>

            <td>{{ hajj_application_item.father_husband_name.label_tag }}</td>
            <td>{{ hajj_application_item.father_husband_name }}</td>

            <td>{{ hajj_application_item.passport_no.label_tag }}</td>
            <td>{{ hajj_application_item.passport_no }}</td>

            <td>{{ hajj_application_item.date_of_expiry.label_tag }}</td>
            <td>{{ hajj_application_item.date_of_expiry }}</td>

            <td>{{ hajj_application_item.date_of_birth.label_tag }}</td>
            <td>{{ hajj_application_item.date_of_birth }}</td>
        </tr>

        <!-- Row 3 -->
        <tr>
            <td>{{ hajj_application_item.nadra_id_card_no.label_tag }}</td>
            <td>{{ hajj_application_item.nadra_id_card_no }}</td>

            <td>{{ hajj_application_item.blood_group.label_tag }}</td>
            <td>{{ hajj_application_item.blood_group }}</td>

            <td>{{ hajj_application_item.gender.label_tag }}</td>
            <td>{{ hajj_application_item.gender }}</td>

            <td>{{ hajj_application_item.fiqah.label_tag }}</td>
            <td>{{ hajj_application_item.fiqah }}</td>

            <td>{{ hajj_application_item.are_you_married.label_tag }}</td>
            <td>{{ hajj_application_item.are_you_married }}</td>

            <td>{{ hajj_application_item.present_postal_address.label_tag }}</td>
            <td>{{ hajj_application_item.present_postal_address }}</td>

            <td>{{ hajj_application_item.tehsil_code.label_tag }}</td>
            <td>{{ hajj_application_item.tehsil_code }}</td>
        </tr>

        <!-- Row 4 -->
        <tr>
            <td>{{ hajj_application_item.mobile_no.label_tag }}</td>
            <td>{{ hajj_application_item.mobile_no }}</td>

            <td>{{ hajj_application_item.telephone_no.label_tag }}</td>
            <td>{{ hajj_application_item.telephone_no }}</td>

            <td>{{ hajj_application_item.performed_hajj_in_last_five_years.label_tag }}</td>
            <td>{{ hajj_application_item.performed_hajj_in_last_five_years }}</td>

            <td>{{ hajj_application_item.want_to_perform_hajj_e_badal.label_tag }}</td>
            <td>{{ hajj_application_item.want_to_perform_hajj_e_badal }}</td>

            <td>{{ hajj_application_item.want_to_perform_hajj_as_group_worker.label_tag }}</td>
            <td>{{ hajj_application_item.want_to_perform_hajj_as_group_worker }}</td>

            <td>{{ hajj_application_item.are_you_mehram_of_a_lady.label_tag }}</td>
            <td>{{ hajj_application_item.are_you_mehram_of_a_lady }}</td>

            <td>{{ hajj_application_item.cnic_no_of_lady.label_tag }}</td>
            <td>{{ hajj_application_item.cnic_no_of_lady }}</td>
        </tr>

        <!-- Row 5 -->
        <tr>
            <td>{{ hajj_application_item.nominee_name.label_tag }}</td>
            <td>{{ hajj_application_item.nominee_name }}</td>

            <td>{{ hajj_application_item.relationship_with_nominee.label_tag }}</td>
            <td>{{ hajj_application_item.relationship_with_nominee }}</td>

            <td>{{ hajj_application_item.nominee_cnic_no.label_tag }}</td>
            <td>{{ hajj_application_item.nominee_cnic_no }}</td>

            <td>{{ hajj_application_item.nominee_mobile_no.label_tag }}</td>
            <td>{{ hajj_application_item.nominee_mobile_no }}</td>

            <td>{{ hajj_application_item.nominee_telephone_no.label_tag }}</td>
            <td>{{ hajj_application_item.nominee_telephone_no }}</td>
        </tr>

        <!-- Row 6 -->
        <tr>
            <td>{{ hajj_application_item.emergency_name_of_person.label_tag }}</td>
            <td>{{ hajj_application_item.emergency_name_of_person }}</td>

            <td>{{ hajj_application_item.emergency_relationship.label_tag }}</td>
            <td>{{ hajj_application_item.emergency_relationship }}</td>

            <td>{{ hajj_application_item.emergency_cell_no.label_tag }}</td>
            <td>{{ hajj_application_item.emergency_cell_no }}</td>
        </tr>

        <!-- Row 7 -->
        <tr>
            <td>{{ hajj_application_item.mehram_application_no.label_tag }}</td>
            <td>{{ hajj_application_item.mehram_application_no }}</td>

            <td>{{ hajj_application_item.mehram_code.label_tag }}</td>
            <td>{{ hajj_application_item.mehram_code }}</td>

            <td>{{ hajj_application_item.mehram_relationship.label_tag }}</td>
            <td>{{ form.mehram_relationship }}</td>
        </tr>

        </tbody>
    </table>
    <div class="row actionButtons ">
        <div class="float-right " style="margin-right: 50px;">
            <button type="button" id="addClient" name="addClient" value="Cancel"
                    class="button-red btn-sm"
                    onClick="javascript:history.go(-1);"><i class="fa fa-chevron-left"
                                                            aria-hidden="true"></i> back
            </button>
        </div>
        <div class="float-right " style="margin-right: 10px;">
            <button type="button" id="addClient" name="addClient" value="Cancel"
                    class="button-blue btn-sm"
                    onclick="javascript:window.location.href='/'"><i class="fa fa-home"
                                                                     aria-hidden="true"></i> home
            </button>
        </div>
    </div>
{% endblock %}

{#page specific js files#}
{#{% block page_js %}#}
{#    <script src="{% static 'js/print/print.min.js' %}"></script>#}
{#{% endblock %}#}

{#page specific inline js#}
{#{% block page_inline_js %}#}
{#    <script>#}
{##}
{##}
{#        $(document).on('click', '#print-btn', function () {#}
{##}
{##}
{#            $("#barcode").printElement(#}
{#                {#}
{#                    leaveOpen: true,#}
{#                    printMode: 'popup'#}
{#                });#}
{#        });#}
{##}
{#        $(document).on('click', '#generate_barcode', function () {#}
{#            var prePopulate;#}
{#            $.ajax({#}
{#                type: 'POST',#}
{#                url: "/barcodes/generate/",#}
{#                data: {#}
{#                    barcode: $('#id_barcode').val(),#}
{#                    name: $('#id_name').val(),#}
{#                    csrfmiddlewaretoken: '{{ csrf_token }}'#}
{#                },#}
{#                success: function (data) {#}
{#                    prePopulate = $.parseJSON(data);#}
{#                    html = '<img style="height:57px; width: 35%;" id="barcode_img" src="/media/product_images/' + prePopulate.company + '/barcodes/' + prePopulate.image + '.png"  alt="barcode"/><button type="button" class="btn btn-inline btn-secondary btn-sm" id="print-btn"><i class="fa fa-print"></i></button>';#}
{#                    $('#barcode').html(html);#}
{#                    $('#id_bar_image_path').val(prePopulate.bar_image_path)#}
{##}
{#                }#}
{#            });#}
{#            return false;#}
{#        });#}
{#        //barcodes end#}
{##}
{#        $("form").submit(function (event) {#}
{#            alertify.success('Product updated!');#}
{#        });#}
{##}
{#        $(document).ready(function () {#}
{#            $(document).on("click", "#updateProduct", function () {#}
{#                $('#updateproduct').submit();#}
{#            });#}
{##}
{#            //select value on click#}
{#            $(function () {#}
{#                $(document).on('click', 'input[type=text], input[type=number]', function () {#}
{#                    this.select();#}
{#                });#}
{#            });#}
{##}
{#            $(document).on('keyup', '#id_purchase_price', function () {#}
{#                var purchase_price = $(this).val();#}
{#                var percent = $('#id_margin').val() || 0;#}
{#                var sale_price = parseFloat(purchase_price) + (parseFloat(purchase_price) * (parseFloat(percent) / 100));#}
{#                $('#id_sale_price').val(parseFloat(sale_price).toFixed(3));#}
{##}
{#            });#}
{##}
{#            $(document).on('keyup', '#id_margin', function () {#}
{#                var purchase_price = $('#id_purchase_price').val();#}
{#                var percent = $(this).val();#}
{#                var sale_price = parseFloat(purchase_price) + (parseFloat(purchase_price) * (parseFloat(percent) / 100));#}
{#                $('#id_sale_price').val(parseFloat(sale_price).toFixed(3));#}
{##}
{#            });#}
{##}
{##}
{#            $(document).on('keyup', '#id_sale_price', function () {#}
{#                var purchase_price = $('#id_purchase_price').val();#}
{#                var sale_price = $(this).val();#}
{#                var percent = 100 * ((parseFloat(sale_price) - parseFloat(purchase_price)) / parseFloat(purchase_price));#}
{#                $('#id_margin').val(parseFloat(percent).toFixed(3));#}
{##}
{#            });#}
{##}
{#preview image#}
{##}
{#            function preview_img(input) {#}
{#                if (input.files && input.files[0]) {#}
{#                    var reader = new FileReader();#}
{##}
{#                    reader.onload = function (e) {#}
{#                        $('#product_image').attr('src', e.target.result);#}
{#                    }#}
{##}
{#                    reader.readAsDataURL(input.files[0]);#}
{#                }#}
{#            }#}
{##}
{#            $('#id_image').on('change', function () {#}
{#                preview_img(this);#}
{#            });#}
{##}
{##}
{#        sub category#}
{#            $('#id_category').change(function () {#}
{#                id = $(this).val();#}
{#                request_url = '/products/get_subcats?id=' + id;#}
{#                $.ajax({#}
{#                    url: request_url,#}
{#                    success: function (data) {#}
{#                        var vals = '<option selected="selected" value="" disabled="disabled">Please select a sub-category</option>';#}
{#                        prePopulate = $.parseJSON(data);#}
{#                        $.each(prePopulate, function (key, value) {#}
{#                            vals += '<option value="' + value.id + '">' + value.name + '</option>';#}
{#                        });#}
{#                        $('#id_subcategory').html(vals);#}
{#                        $('#subcat').css('display', 'block');#}
{#                    }#}
{#                })#}
{#            })#}
{##}
{#        });#}
{#    </script>#}
{#{% endblock %}#}

templates/hajj_application/hajjapplication_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Delete Application{% endblock %}</title>
{% block content %}
            <div class="heading-container">
                <h5 class="heading">Delete Application</h5>
            </div>
            <div class="ro-outer">
                <a href="{% url 'hajj_application:list' %}">
                    <span class=" new_button button-green"> All Applications </span>
                </a>
                <span type="button" class="close_btn button-red" aria-hidden="true" onClick="javascript:history.go(-1);">X</span>
            </div>
            <div class="form-container">
                    <form method="post">
                        {% csrf_token %}
                        <p style="color:red;">Are you sure you want to delete <span
                                style="color:grey;">Hajj Application</span>?</p>
                        {{ form }}
                        <input type="submit" class=" button-red btn-sm" value="Confirm"/>
                        <a href="{% url 'hajj_application:list' %}">
                            <button type="button" class=" button-blue btn-sm">Cancel</button>
                        </a>
                    </form>
            </div>

            <div class="row actionButtons ">

                 <div class="float-right " style="margin-right: 50px;">
                        <button type="button" id="addClient" name="addClient" value="Cancel"
                                class="button-red btn-sm"
                                onClick="javascript:history.go(-1);"><i class="fa fa-chevron-left"
                                                                        aria-hidden="true"></i> back
                        </button>
                    </div>
                    <div class="float-right " style="margin-right: 10px;">
                        <button type="button" id="addClient" name="addClient" value="Cancel"
                                class="button-blue btn-sm"
                                onclick="javascript:window.location.href='/'"><i class="fa fa-home"
                                                                                 aria-hidden="true"></i> home
                        </button>
                    </div>
            </div>
{% endblock %}
{% block page_inline_js %}
    <script>

    </script>
{% endblock %}

templates/hajj_application/list.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}All Applications{% endblock %}</title>
{% block content %}
            <div class="heading-container">
                <h5 class="heading">All Applications</h5>
            </div>
            <div class="ro-outer">
                <a href="{% url 'hajj_application:add' %}">
                    <span class=" new_button button-green ">New Application</span>
                </a>
                <span type="button" class="close_btn button-red" aria-hidden="true" onClick="javascript:history.go(-1);">X</span>
            </div>
            <table id="list" >
                <thead>
                <tr>
                    <th>Hajj Application #</th>
                    <th>Name of Applicant</th>
                    <th>Father/Husband Name</th>
                    <th>Contact#</th>
                    <th>Enrollment#</th>
                    <th>Package Name</th>
                    <th>Actions</th>
                </tr>
                </thead>
                {% for item in hajj_application_items %}
                    <tr>
                        <td><a href="{% url "hajj_application:detail" item.pk %}"
                               style="text-decoration: none; border: 0;">{{ item.hajj_application_no }}</a></td>
                        <td>{{ item.name_of_applicant_as_per_passport }}</td>
                        <td>{{ item.father_husband_name }}</td>
                        <td>{{ item.mobile_no }}</td>
                        <td>{{ item.enrollment_no }}</td>
                        <td>{{ item.package }}</td>
                         <td><a href="{% url "hajj_application:update" item.pk %}"
                               style="text-decoration: none; border: 0;margin-right: 20px;"><i
                                class="fa fa-pencil-square-o"
                                aria-hidden="true"></i></a>
                            <a href="{% url "hajj_application:delete" item.pk %}"
                               style="text-decoration: none; border: 0;color:red;margin-right: 20px;"><i
                                    class="fa fa-trash-o"
                                    aria-hidden="true"></i></a>
                            <a href="{% url "hajj_application:detail" item.pk %}"
                               style="text-decoration: none; border: 0;margin-right: 20px;"><i class="fa fa-expand" aria-hidden="true"></i></a>
                        </td>

                    </tr>
                {% endfor %}
            </table>
            <div class="row actionButtons ">
        <div class="float-right " style="margin-right: 50px;">
            <button type="button" id="addClient" name="addClient" value="Cancel"
                    class="button-red btn-sm"
                    onClick="javascript:history.go(-1);"><i class="fa fa-chevron-left"
                                                            aria-hidden="true"></i> back
            </button>
        </div>
        <div class="float-right " style="margin-right: 10px;">
            <button type="button" id="addClient" name="addClient" value="Cancel"
                    class="button-blue btn-sm"
                    onclick="javascript:window.location.href='/'"><i class="fa fa-home"
                                                                     aria-hidden="true"></i> home
            </button>
        </div>
            </div>

{% endblock %}
{% block page_inline_js %}
    <script>
        $(document).ready(function () {
            $('#list').DataTable({
                stateSave: true
            });
        });
    </script>

{% endblock %}